#server:
#  port: 15262
#  error.whitelabel.enabled: false
#  tomcat:
#    accesslog.enabled: true
#    max-threads: 30
#  servlet.context-path: /devicescacheupdater
    
#logging:
#  level:
#    org.springframework.web: INFO
#    org.hibernate: ERROR
#    es.fermax.logging.aop: DEBUG
#  file: "target/devicecacheupdater-service.log"

swagger:
  host: localhost:8080

# Specify the DNS URI of your Redis cache.
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true

